### ISSUE TITLE
clone animation data in readme sample

### ISSUE THREAD

**Issue by benitogf** [hanorine/react-lottie-hook#3]
hello, thanks for making this project 🥇 💯 

small suggestion, I spent better part of day trying to figure out a memory leak issue: https://github.com/airbnb/lottie-web/issues/1933#issuecomment-867345916 

maybe including the animation data being cloned in the readme sample code would be nice, happy to make a PR for it

**Comment by hanorine** [comment]
Thank you for your feedback and sorry for the overdue reply.

If you're still willing to make that PR please do. Otherwise I'll figure out some good time to do it myself.

Thanks again.

**Comment by benitogf** [comment]
do you think that changing the example to this is ok? 

```js
import React from "react";
import { useLottie, Lottie } from "react-lottie-hook";
import animationData from "./animation.json";

const App = () => {
  const [lottieRef, { isPaused, isStopped }, controls] = useLottie({
    renderer: "svg",
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice",
      progressiveLoad: false,
    },
    JSON.parse(JSON.stringify(animationData)),
  });

  return <Lottie lottieRef={ref} width={400} height={400} />;
};
```

or should the example introduce the lodash.cloneDeep dependency? 

also including a comment referring to the [issue](https://github.com/airbnb/lottie-web/issues/1933)?

**Comment by hanorine** [comment]
yeah that looks good. The less dependencies we include in the example the better; allowing any developer to choose their own way.

**Comment by hanorine** [comment]
I would suggest though to add a side note after the example that due to memory leaks it is advised to deeply clone the animation object using methods such as `lodash.cloneDeep`.
